version: '3.8'

services:
#  vue:
#    build: ./frontend
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    ports:
#      - 80:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
  php:
    build: ./backend
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=programa_estudos
      - DB_USERNAME=mysql
      - DB_PASSWORD=mypass
    volumes:
      - ./backend:/var/www/html
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: programa_estudos
    ports:
      - 3306:3306
  adminer:
    image: adminer:4.7.7-standalone
    ports:
      - 8081:8080
    depends_on:
      - db
  flyway:
    image: flyway/flyway:6.4.4
    command: -url=jdbc:mysql://db -schemas=programa_estudos -user=mysql -password=mypass -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db